### ISSUE TITLE
raise exception if intermediate mix has insufficient volume to create a downstream mix

### ISSUE THREAD

**Issue by dave-doty** [DNA-and-Natural-Algorithms-Group/alhambra#17]
TODO: give example of what sort of mix this should raise error on.

**Comment by cgevans** [comment]
It might be useful to have this as a function that takes potentially 
multiple mixes, and then have it check to make sure all of those mixes 
can be made, rather than having it be a method on one mix.

**Comment by dave-doty** [comment]
> It might be useful to have this as a function that takes potentially multiple mixes, and then have it check to make sure all of those mixes can be made, rather than having it be a method on one mix.

I was thinking it would not be a method, but a check done when creating a mix, which raises an exception if an "input" mix has insufficient volume.
