### ISSUE TITLE
fix `VisibleDeprecationWarning` from stickydesign when importing alhambra.mixes

### ISSUE THREAD

**Issue by dave-doty** [DNA-and-Natural-Algorithms-Group/alhambra#39]
Importing alhambra.mixes causes a deprecation warning to appear from [stickydesign](https://github.com/DNA-and-Natural-Algorithms-Group/stickydesign):

```
/home/ddoty/.local/lib/python3.10/site-packages/stickydesign/stickydesign2/seqclasses.py:12: 
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences 
(which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) 
is deprecated. If you meant to do this, you must specify 'dtype=object' when creating 
the ndarray.
  _BSA_TO_SA_ARRAYS = np.array([
```

I would have filed this in https://github.com/DNA-and-Natural-Algorithms-Group/stickydesign/issues/new, but actually the warning does not appear simply by importing stickydesign:

```python
$ python
Python 3.10.2 (main, Jan 15 2022, 18:02:07) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stickydesign
>>>
```

So I'm not sure what the issue is or how to fix it (probably does have to be fixed in stickydesign).

**Comment by cgevans** [comment]
This should now be fixed.

**Comment by dave-doty** [comment]
> This should now be fixed.

Does it require pulling/installing the latest stickydesign?

**Comment by cgevans** [comment]
If you're installing alhambra with pip, then it should be automatic.  Otherwise, you need to install the latest stickydesign, but only need 0.8.3, not the github main branch (eg, `pip install -U stickydesign` will work).
