### ISSUE TITLE
round floating-point values near 0 to 0

### ISSUE THREAD

**Issue by dave-doty** [DNA-and-Natural-Algorithms-Group/alhambra#5]
Small floating point errors result in strange mix reports. For example, if I have 5 strands at 200 uM each and want to mix them using `MultiFixedConcentration` to get to 40 uM each, clearly I should just mix equal quantities of each with nothing else. 

```python
# strands has 5 strands, each 200 uM
mix = am.Mix(
    actions=[am.MultiFixedConcentration(components=strands, fixed_concentration="40 uM", set_name='strands')],
    name="strands",
    fixed_total_volume="250 uL",
)
mix = mix.with_reference(reference)
print(mix.table())
```

But I'm told I need 56.84 zeptoliters of buffer:

| Comp                         | Src []    | Dest []   | #   | Ea Tx Vol   | Tot Tx Vol   | Loc                                     | Note   |
|:-----------------------------|:----------|:----------|:----|:------------|:-------------|:----------------------------------------|:-------|
| mon0, mon1, mon2, mon3, mon4 | 200.00 µM | 40.00 µM  | 5   | 50.00 µl    | 250.00 µl    | 5 monomer synthesis: A1, B1, C1, D1, E1 |        |
| Buffer                       |           |           |     |             | 56.84 zl     |                                         |        |
| *Total:*                     |           | 40.00 µM  |     |             | 250.00 µl    |                                         |        |

**Comment by dave-doty** [comment]
Hmm, this seems to becoming from the pint library that defines the `Quantity` object, and doesn't seem straightforward to fix. Despite the phrasing of the issue I intended it to be a bit more general, such as rounding 19.9999994 uL to 20 uL, or more generally rounding pipetting quantities to 2 decimal places in whatever units they are. Given that pint library is specifically designed to work with units, one would hope there's a way to do this within that library. In other words, use the units to define how much to round the absolute floating-point number under the hood.

**Comment by cgevans** [comment]
Actually, it seems like there are some larger float problems with pint here: since it is using M and L as the base units here, the unit conversions involve multiplying by, eg, 1e-6 or 1e-9 and then 1e6 or 1e9, which isn't ideal.

The quantities currently are rounded on printing by pint, but they're rounding relatively, which is why we get the zL there.

I'm currently seeing if I can improve the floating point error situation.

**Comment by cgevans** [comment]
Hmm... so, in order to fully solve this problem, at the cost of making things slower, I've tried to switch volumes and concentrations to use decimal.Decimal instead of float.  This should solve the problem without needing to round.

**Comment by dave-doty** [comment]
PR #7 looks like it addresses this.

But I'm getting an error though for a similar use case. The following code should result in saying we need 100 uL of each of strand 1 and strand 2:

```python
import alhambra.mixes as am
strands = [
    am.Strand(name='strand 1', concentration="200 uM", plate='plate 1', well='A1', sequence='AAA'), 
    am.Strand(name='strand 2', concentration="200 uM", plate='plate 1', well='A2', sequence='CCC'),
]
mix = am.Mix(
    actions=[
        am.MultiFixedConcentration(components=strands, fixed_concentration="100 uM", set_name='mix')
    ],
    name="mix",
    fixed_total_volume="200 uL",
)
print(mix.table())
```

But instead it generates this exception:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [31], in <module>
      4 strands = [
      5     am.Strand(name='strand 1', concentration="200 uM", plate='plate 1', well='A1', sequence='AAA'), 
      6     am.Strand(name='strand 2', concentration="200 uM", plate='plate 1', well='A2', sequence='CCC'),
      7 ]
      8 mix = am.Mix(
      9     actions=[
     10         am.MultiFixedConcentration(components=strands, fixed_concentration="100 uM", set_name='mix')
   (...)
     13     fixed_total_volume="200 uL",
     14 )
---> 15 print(mix.table())

File /mnt/c/Dropbox/git/alhambra/src/alhambra/mixes.py:1548, in table(self, tablefmt, validate)
   1544 @property
   1545 def buffer_volume(self) -> Quantity[Decimal]:
   1546     """
   1547     The volume of buffer to be added to the mix, in addition to the components.
-> 1548     """
   1549     mvol = sum(c.tx_volume(self.total_volume) for c in self.actions)
   1550     return self.total_volume - mvol

File /mnt/c/Dropbox/git/alhambra/src/alhambra/mixes.py:1545, in table(self, tablefmt, validate)
   1535     else:
   1536         return sum(
   1537             [
   1538                 c.tx_volume(self.fixed_total_volume or Q_(DNAN, ureg.uL))
   (...)
   1541             Q_(Decimal(0.0), ureg.uL),
   1542         )
   1544 @property
-> 1545 def buffer_volume(self) -> Quantity[Decimal]:
   1546     """
   1547     The volume of buffer to be added to the mix, in addition to the components.
   1548     """
   1549     mvol = sum(c.tx_volume(self.total_volume) for c in self.actions)

File /mnt/c/Dropbox/git/alhambra/src/alhambra/mixes.py:1581, in validate(self, mixlines)
   1573 mixlines.append(
   1574     MixLine("*Total:*", None, self.concentration, self.total_volume)
   1575 )
   1577 include_numbers = any(ml.number != 1 for ml in mixlines)
   1579 return tabulate(
   1580     [ml.toline(include_numbers) for ml in mixlines],
-> 1581     MIXHEAD_EA if include_numbers else MIXHEAD_NO_EA,
   1582     tablefmt=tablefmt,
   1583 )

ValueError: ('Some volumes are negative.', '| Comp               | Src []    | Dest []   | #   | Ea Tx Vol   | Tot Tx Vol   | Loc             | Note   |\n|:-------------------|:----------|:----------|:----|:------------|:-------------|:----------------|:-------|\n| strand 1, strand 2 | 200.00 µM | 100.00 µM | 2   | 100.00 µl   | 200.00 µl    | plate 1: A1, A2 |        |\n| Buffer             |           |           |     |             | -28.42 zl    |                 |        |\n| *Total:*           |           | 100.00 µM |     |             | 200.00 µl    |                 |        |')
```

Actually that exception is just a special case of requesting a concentration that is too high to achieve. For example, since both strands are 200 uM, the maximum we could get mixing them is 100 uM, and if we request 150 uM:

```python
am.MultiFixedConcentration(components=strands, fixed_concentration="150 uM", set_name='mix')
```

We get the same error. But the floating point rounding error here means it's actually incorrect behavior when the requested concentration is 100 uM, which is possible in principle. (In the case of requesting 150 uM, it's not valid for the caller to request that, but would probably be good to check for that and raise a more descriptive exception.)

**Comment by cgevans** [comment]
With #7, the first one there (exactly 0 µL buffer) now works.

The second should certainly give a better error.  The initial hope there was that I could provide the table with negative values, and it would be formatted when the exception was displayed.  But it looks like that doesn't work, because newlines aren't printed.

**Comment by cgevans** [comment]
This should be fixed at this point, both in terms of exact values, and in terms of error messages.  Please reopen it if it shows up again.
