### ISSUE TITLE
track volumes across mixes within an experiment, and across experiments

### ISSUE THREAD

**Issue by dave-doty** [DNA-and-Natural-Algorithms-Group/alhambra#53]
## Track volumes across mixes in one experiment
It would be useful to track volumes across different mixes to ensure that sufficient volumes are available.

First, when using an intermediate mix `m1` in downstream mixes, we currently have fairly primitive error-handling. For example, if the volume of `m1` is 100 uL, then an error is issued if more than 100 uL of `m1` is required in a downstream mix `m2`. However, suppose `m1` is required in *two* downstream mixes `m2` and `m3`, each requiring 60 uL of `m1`. No error is given because 60 < 100, even though a total of 120 uL of `m1` is required for both `m2` and `m3`.

This could be handled by a new class `Experiment`, which can track several related mixes used in a single experiment and issue an error if the total volumes don't add up.

## Track volumes across experiments
A trickier problem is tracking volumes across different experiments for re-used mixes or strand stocks. This is trickier because, unlike the idea for the `Experiment` object above, this would require persisting the volume remaining in strand stocks or re-used mixes to disk in a database. The reason this is tricky is that one often re-runs the same code repeatedly to debug, and we would not want that to affect the stored volumes in the database.

One idea would be to use a "functional programming style". Maintain the database as a ordered sequence of files, each file associated to a single experiment. One could introduce a new object called `Project`, and just like multiple `Mix`'s can be associated to an `Experiment`, multiple `Experiment`'s can be associated to a `Project`. The `Project` would be responsible for maintaining an order on the experiments, and when running code for one experiment, it reads the database file of the previous experiment, say `exp7`, and writes a new one `exp8`. If the code is re-run, then this only overwrites the files for `exp8`.

**Comment by cgevans** [comment]
Closing this here, and moving it to cgevans/mixes.
