### ISSUE TITLE
ModuleNotFoundError when using Pint version 0.19

### ISSUE THREAD

**Issue by DanielHader** [DNA-and-Natural-Algorithms-Group/alhambra#55]
When using Pint version 0.19 (released only a month ago) I get the error
ModuleNotFoundError: No module named 'pint.quantity'
from line 52 of mixes.py

It seems to work fine with Pint version 0.18 installed instead

**Comment by cgevans** [comment]
That's rather strange: if you just try `import pint.quantity` in Python with pint 0.19 installed, does it have the same error?

**Comment by cgevans** [comment]
The mixes portion of alhambra has now been moved to <https://github.com/cgevans/mixes>, and this bug is fixed there.
